### Authenticate as Store Manager and save token
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "manager@example.com",
  "password": "managerPassword"
}

> {%
    client.assert(response.body.token, "Token is not generated");
    client.global.set("manager-token", response.body.token);
%}

### Get All Stores (Store Manager the pselects one)
POST http://localhost:8080/api/stores/
Content-Type: application/json
Authorization: Bearer {{manager-token}}