# Super Admin login flow

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminPassword"
}

> {%
    client.global.set("auth-token", response.body.token);
%}

### Create Category
POST http://localhost:8080/api/categories/create
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "name": "Electronics"
}

> {%
    client.global.set("category-id", response.body.id);
%}

### Update Category
PUT http://localhost:8080/api/categories/update/{{category-id}}
Content-Type: application/json
Authorization: Bearer {{auth-token}}


{
  "name": "Technology"
}

### Get Category by ID
GET http://localhost:8080/api/categories/{{category-id}}
Content-Type: application/json
Authorization: Bearer {{auth-token}}

### Delete Category by ID
DELETE http://localhost:8080/api/categories/delete/{{category-id}}
Content-Type: application/json
Authorization: Bearer {{auth-token}}