### Authenticate as Store Manager
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "manager@example.com",
  "password": "managerPassword"
}

> {%
    client.global.set("auth-tok", response.body.token);
%}
