### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "Gae",
  "lastname": "Bar",
  "email": "gae@mail.com",
  "password": "password",
  "role": "ADMIN"
}

> {%
    client.global.set("auth-token", response.body.token);
%}

### Query the Authenticate endpoint
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "gae@mail.com",
  "password": "password"
}