### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "Gae",
  "lastname": "Bar",
  "email": "gae@mail.com",
  "password": "password",
  "role": "ADMIN"
}

### Query the Authenticate endpoint
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "gae@mail.com",
  "password": "password"
}

> {%
    client.global.set("auth-token", response.body.token);
%}


### Create first store
POST http://localhost:8080/admin/createStore
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "name": "Redmond Megastore",
  "location": "123 Red Street, Redmond, WA 98074",
  "contactInformation": "Telephone Number: 1234567890",
  "storeType": "retail",
  "openingDate": "2019-01-01"
}


### Create second store
POST http://localhost:8080/admin/createStore
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "name": "Seattle Megastore",
  "location": "123 Blue Street, Seattle, WA 98074",
  "contactInformation": "Telephone Number: 3432343434",
  "storeType": "warehouse",
  "openingDate": "2020-01-10"
}
